Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [5]:
import numpy as np

In [3]:
N = int(input('Введите число:'))
np.arange(N, 0, -1)

Введите число:7


array([7, 6, 5, 4, 3, 2, 1])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [5]:
N = int(input('Введите число:'))
diag_matrix = np.diag(np.arange(N, 0, -5), k=0)
print(diag_matrix)

Введите число:23
[[23  0  0  0  0]
 [ 0 18  0  0  0]
 [ 0  0 13  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0  3]]


In [6]:
np.trace(diag_matrix)


65

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [3]:
from numpy import linalg
mat = np.array([[4., 2., 1.], [1., 3., 0.], [0., 5., 4.]])
vec = np.array([4., 12., -3.])
linalg.solve(mat, vec)

array([ 0.46666667,  3.84444444, -5.55555556])

In [4]:
np.allclose( np.dot(mat, linalg.solve(mat, vec)), vec )

True

Имеется матрица покупок в интернет-магазине. 
Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.
На сайт заходит очередной посетитель, о покупках которого известно следующее:next_user_stats = np.array([0, 1, 2, 0, 0, 0])
Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [14]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [15]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [18]:
from numpy import linalg
for user in users_stats:
    length_user = np.linalg.norm( user )
    length_next_user = np.linalg.norm( next_user_stats )
    
    print(np.dot( user, next_user_stats )/( length_user * length_next_user ))

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0


In [16]:
# Попытка сделать задачу с помощью spicy, но ответы неверны. Почему - ответить не могу
import scipy.spatial.distance as ds
for user in users_stats:
    dis = ds.cosine(user, next_user_stats)
    print(dis)

0.8
0.15484574527148343
0.6000000000000001
0.20943058495790523
0.6000000000000001
1.0
1.0
0.05131670194948623
1.0
1.0
